/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Oogiri App API
 * チャットでのテーマ・メッセージ投稿以外のAPIエンドポイントを提供します。 ユーザー登録、ログイン、プロフィール更新、グループ作成、招待、回答、いいね、の機能を提供します。

 * OpenAPI spec version: 1.0.0
 */
import type { Answer, GetThemeAnswer } from "../oogiriAppAPI.schemas";

import { customInstance } from "../../../lib/custom-instance";

export const getAnswers = () => {
  /**
   * テーマに対する回答を投稿します。{messageId} == parentId
   * @summary テーマへの回答
   */
  const postAnswersMessageId = (messageId: string, answer: Answer) => {
    return customInstance<void>({
      url: `/answers/${messageId}`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: answer,
    });
  };
  /**
   * テーマに対する回答を取得します。{messageId} == parentId
   * @summary 回答取得
   */
  const getAnswersMessageId = (messageId: string) => {
    return customInstance<GetThemeAnswer[]>({
      url: `/answers/${messageId}`,
      method: "GET",
      headers: { "Content-Type": "application/json" },
    });
  };
  return { postAnswersMessageId, getAnswersMessageId };
};
export type PostAnswersMessageIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnswers>["postAnswersMessageId"]>>
>;
export type GetAnswersMessageIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnswers>["getAnswersMessageId"]>>
>;
