openapi: 3.0.1
info:
  title: wa-life API
  version: 1.0.0
servers:
  - url: https://*/dev/
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
