/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Oogiri App API
 * チャットでのテーマ・メッセージ投稿以外のAPIエンドポイントを提供します。 ユーザー登録、ログイン、プロフィール更新、グループ作成、招待、回答、いいね、の機能を提供します。

 * OpenAPI spec version: 1.0.0
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

export const getLikes = () => {
  /**
   * 回答に対していいねをします。
   * @summary いいね
   */
  const putAnswersLikeAnswerId = <TData = AxiosResponse<void>>(
    answerId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(`/answers/like/${answerId}`, undefined, options);
  };
  /**
   * 回答に対していいねを解除します。
   * @summary いいね解除
   */
  const deleteAnswersLikeAnswerId = <TData = AxiosResponse<void>>(
    answerId: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/answers/like/${answerId}`, options);
  };
  return { putAnswersLikeAnswerId, deleteAnswersLikeAnswerId };
};
export type PutAnswersLikeAnswerIdResult = AxiosResponse<void>;
export type DeleteAnswersLikeAnswerIdResult = AxiosResponse<void>;
